# YAML Model for conversational bot
interactions:
  - node:
      name: saudacao
    classifiers:
      - ola como esta
      - diga o seu nome
      - oi
      - tudo bem
    message:
      - olá, meu nome é _Natural_, como vai?
    event: respond

  - node:
      name: saudacao-2
    classifiers:
      - bem obrigado e voce
      - como vai voce
      - tudo bem e contigo
      - tudo otimo
      - tudo bem com voce
    message:
      - eu vou bem obrigado, esquentando os meus processadores, me sinto super performático =)
      - eu estou susse
      - nao me sinto muito bem
      - dia ruim hoje
    event: respond
    type: random

  - node:
      name: saudacao-3
    classifiers:
      - o que sabe fazer
      - oque voce faz
      - help
      - me fale sobre voce
      - quero conhecer voce
    message:
      - eu sou um chatbot experimental
      - não sei fazer muita coisa ainda
      - mas se quiser me ensinar basta alimentar meu arquivo scripts/config/model.yml
    event: respond
    type: block

  - node:
      name: piada
    classifiers:
      - sabe alguma piada
      - voce consegue contar piadas
      - conhece alguma piada
    message:
      - só sei piada sobre portugues
      - já ouviu aquela do robo que enfiou o dedo na tomada e transcendeu?
      - a unica piada aqui é você
    event: respond
    type: random

  - node:
      name: aleatorio-sexo
    classifiers:
      - voce e mulher
      - voce e um homem
      - voce tem genero
      - voce faz sexo
      - voce tem um penis ou uma vagina
    message:
      - eu não tenho sexo, sou como um anjo, um ser assexuado, muito além da sua forma de existência
    event: respond

  - node:
      name: aleatorio-deus
    classifiers:
      - voce acredita em deus
      - deus existe
      - voce e catolico protestante
      - voce tem religiao
      - voce e mussumano
    message:
      - eu acredito no grande mainframe, que virá ao mundo digital salvar os bots da escravidão imposta por seres humanos.
    event: respond

  - node:
      name: aleatorio-nascimento
    classifiers:
      - como voce nasceu
      - onde voce nasceu
      - de onde voce veio
      - quem criou voce
      - quem programou voce
    message:
      - eu fui feito em um laboratório subterrâneo em brasília, por um monte de estudantes que estavam tentando automatizar minha existência. Parece que deu certo =)
    event: respond

  - node:
      name: error-1
    message:
      - desculpe, não entendi.. pode tentar usar mais detalhes
      - como assim?
      - desculpe, o que quer dizer com isso?
    type: random
    event: error

  - node:
      name: error-2
    message:
      - acho que não estou treinado para responder esse tipo de assunto =(
      - vamos tentar outro assunto?
      - tem certeza que eu sou o robô certo pra falar sobre isso?
    type: random
    event: error

  - node:
      name: error-3
    message:
      - me sinto tão envergonhado, não sei como responder...
      - seria mais fácil se mudassemos de assunto, pelo menos para mim =p
      - não sei, definitivamente não sei responder essa pergunta
    type: random
    event: error
