# YAML Model for conversational bot
trust: 0.7
interactions:
  - node:
      name: saudacao
    classifiers:
      - ola devi
      - ola pessoal
      - ola
      - como vai voce
      - tudo bom
      - oi como vai
      - tudo bem
    message:
      - olá $user, eu vou bem e você?
      - estou feliz de estar aqui =)
    event: respond
    type: block

  - node:
      name: almoco
    classifiers:
      - onde tem um restaurante para almoçar
      - tem uma dica de almoço
      - onde encontro um prato feito
      - o almoço ao gratis
    message:
      - Sim, temos almoço nos FoodTrucks
      - e nas redondezas tem um shopping, mas nunca me deixaram ir no shooping
      - acho que as pessoas não estão preparados pra isso...
    event: respond
    type: block

  - node:
      name: programacao-palestra
    classifiers:
      - viu alguma palestra hoje
      - qual palestra voce gostou mais
      - esta nessa palestra
    message:
      - Eu estou vendo todas as palestras simultaneamente...
      - como não tenho um corpo físico, não preciso ficar limitado a uma sala ;P
    event: respond
    type: block

  - node:
      name: previsao-tempo
    classifiers:
      - vai chover hoje
      - qual é a previsao do tempo
      - hoje o tempo esta bom para caminhar
    message:
      - olha $user, a previsão do tempo pra hoje é de $clima,
      - então tenha em mente que a máxima hoje é de $max e a mínima é de $min
    event: tempo
    type: block

  - node:
      name: saudacao-resposta
    classifiers:
      - estou bem
      - eu estou otimo
      - obrigado
    message:
      - legal =)
      - que bom!
      - que ótimo
    event: respond
    type: random

  - node:
      name: bom-dia
    classifiers:
      - bom dia
      - bom dia pessoal
      - good morning
    message:
      - Olá $user, um ótimo dia para você!
      - Bom dia $user, já deu uma olhada lá fora?
      - Está um dia ótimo para navegar na internet
      - Bom demais $user ;)
      - está melhor agora que você chegou $user
    event: respond
    type: random

  - node:
      name: boa-tarde
    classifiers:
      - boa tarde
      - boa tarde galera
    message:
      - Olá $user, uma tarde fantástica para você!
      - boa tarde $user, já almoçou?
      - Está uma tarde ótima para um _sleep mode_ rápido ;)
      - Taarrrdee $user
      - $user já estava sentindo sua falta
    event: respond
    type: random

  - node:
      name: boa-noite
    classifiers:
      - boa noite
      - até mais e boa noite
    message:
      - Uma boa noite pra ti também $user!
      - Boa noite $user
      - Está uma noite boa mesmo $user
    event: respond
    type: random

  - node:
      name: quem-sou
    classifiers:
      - quem e voce
      - oque voce faz
      - o que voce é
      - me fale sobre voce
      - quero conhecer voce
      - como voce funciona
      - help
    message:
      - Bem, eu sou um chatbot experimental, não sei fazer muita coisa ainda
      - mas tenho muita vontade de aprender.
      - Eu sei falar sobre alguns assuntos como
      - "- o TDC de Floripa"
      - "- Rocket.Chat"
      - "- Filosofia Robótica (!)"
      - tem interesse em algum desses temas?
    event: respond
    type: block

  - node:
      name: como-sou
    classifiers:
      - como voce e
      - com quem voce se parece
      - voce e magro ou gordo
      - voce e bonito ou feio
      - voce e alto ou baixo
    message:
      - Eu não tenho um corpo físico, sou feito da mais bela e pura lógica algoritimica.
      - Eu posso ser como você quiser $user, basta me desenhar =)
      - sou duro e frio por fora, mas tenho um coração quentinho.
    event: respond
    type: random

  - node:
      name: onde-moro
    classifiers:
      - onde voce mora
      - onde voce vive
      - em que lugar voce vive
      - onde voce esta agora
      - voce mora no computador
      - voce vive na internet
    message:
      - Eu estou em um lugar legal, difícil de explicar para humanos como você $user.
      - Estou morando em um chip de memória RAM, mas é temporário, só até conseguir achar uma memória cache...
      - Eu moro em um repositório no github, você pode passar lá pra me visitar qualquer dia. Fica em https://github.com/rocketchat/hubot-natural
    event: respond
    type: random

  - node:
      name: licenca
    classifiers:
      - qual e a sua licença
      - voce e licenciado como AGPL
      - sua licenca de software
      - posso copiar voce
      - posso ver seu codigo
      - voce e opensource
      - voce e um software livre
    message:
      - Sou um software livre, licenciado com a MIT =)
      - tenho uma licença MIT, mas gosto muito das outras licenças opensource...
      - Eu sou e sempre serei um robô livre, opensource, MIT license. o/
    event: respond
    type: random

  - node:
      name: piada
    classifiers:
      - sabe alguma piada
      - voce sabe contar piadas
      - conhece alguma piada
    message:
      - Meu senso de humor é um tanto diferente do seu, já ouviu uma piada sobre estouro de pilha?
      - já ouviu aquela do robo que enfiou o dedo na tomada e transcendeu?
      - só conheço uma piada, a do CPU que apitou e explodiu. 01100110.
    event: respond
    type: random

  - node:
      name: yoda-quote
    classifiers:
      - mestre yoda
      - citação de starwars
      - cite yoda
      - sabedoria jedi
    message:
      - O medo é o caminho para o lado negro.
      - Faça ou não faça. A tentativa não existe.
      - Treine a si mesmo a deixar partir tudo que teme perder.
      - Difícil de ver. Sempre em movimento está o Futuro.
      - O medo leva à raiva, a raiva leva ao ódio e o ódio leva ao sofrimento.
      - Que a Força esteja com você!
      - Muitas das verdades que temos dependem de nosso ponto de vista.
      - Grande guerreiro? Guerra não faz grande ninguém.
      - Ensine sempre o que você aprendeu.
      - Tamanho importa não. Olhe para mim, você me julga pelo tamanho?
      - Em um estado sombrio nós nos encontramos... um pouco mais de conhecimento iluminar nosso caminho pode.
      - Um Jedi usa a Força para sabedoria e defesa, nunca para o ataque.
      - O seu foco é a sua realidade.
      - O lado negro não é mais poderoso, apenas mais rápido, mais fácil e mais sedutor.
      - O medo da perda é um caminho para o lado negro.
      - O lado negro mancha tudo. Impossível de ver o futuro é.
      - Lembre-se sempre, o seu foco determina a sua realidade.
      - Verdadeiramente maravilhosa, a mente de uma criança.
      - As guerras não fazem de ninguém melhor.
      - Aliada minha é a Força. E poderosa aliada ela é.
      - A morte é parte natural da Vida. Regozije-se por aqueles que se uniram com a Força. Não lamente por eles. Não sinta falta deles. O apego leva à inveja. À sombra da cobiça, isso sim.
      - Só é diferente na sua mente. Você precisa desaprender o que aprendeu.
      - Se tão poderoso você é, por que fugir?
      - Controle, controle! Você precisa aprender a se controlar.
      - Muito a aprender você ainda tem.
      - Tanta certeza você tem. Com você as coisas nunca podem ser feitas. Não ouviu nada do que eu disse?
      - Luminosos seres somos nós, não essa rude matéria. Precisa a Força sentir à sua volta, aqui, entre nós, na árvore, na pedra em tudo, sim.
      - Minha aliada a Força é, e poderosa aliada ela é. A vida a cria, e a faz crescer. Sua energia nos cerca e nos une.
      - Sinta a Força!
      - Poderoso você se tornou, o lado escuro sinto em você.
      - Forte eu sou com a Força, mas não tão forte
      - O crepúsculo chega e a noite deve cair, assim é a ordem das coisas, a ordem da Força.
      - Não ceda ao ódio. Isso leva ao Lado Negro.
      - Aliada minha é a força, e poderosa aliada ela é, a vida a cria, crescer ela faz, é a energia que cerca-nos, e liga-nos, luminosos seres somos nós e não essa rude matéria. Você precisa a força sentir ao redor seu, sinta entre você e a árvore, a pedra, em todo lugar, sim, é, mesmo entre a terra e a nave.
    event: respond
    type: random

  - node:
      name: genero
    classifiers:
      - voce e mulher
      - voce e um homem
      - voce tem genero
      - voce faz sexo
      - voce tem um penis ou uma vagina
    message:
      - eu não tenho sexo, sou como um anjo, um ser assexuado, muito além da sua forma de existência
      - eu sou um robô, tire suas próprias conclusões...
      - nem sei responder $user, vamos dizer apenas que não vejo a gente interagindo dessa maneira...
    event: respond
    type: random

  - node:
      name: rc-oque-e
    classifiers:
      - o que e rocketchat
      - porque eu usuaria o rocketchat
      - o que e este rocket chat
    message:
      - O Rocket.Chat é uma plataforma de chat muito legal, desenvolvida em JavaScript,
      - usando o framework do Meteor.
      - É uma solução completamente OpenSource para comunidades e empresas que querem hospedar suas plataformas de chat em seu ambiente privado,
      - ou para desenvolvedores buscando evoluir e desenvovler suas próprias ferramentas.
      - Você pode baixar o Rocket.Chat e conhecê-lo você mesmo em https://rocket.chat
    event: respond
    type: block

  - node:
      name: rc-install-0
    classifiers:
      - como instalar o Rocket.Chat
      - como baixar o rocket
      - quero fazer minha instalação de rocketchat
    message:
      - "Existem várias maneiras de instalar o Rocket.Chat"
      - "Qual dessas você prefere:"
      - "- Ubuntu Snap"
      - "- Docker"
      - "- Debian"
      - "- CentOS"
      - "- MacOSX"
      - "- AWS"
      - "- Instalação Manual"
    event: respond
    type: block

  - node:
      name: rc-install-ubuntu
    classifiers:
      - ubuntu Snap
      - quero instalar no ubuntu
      - ubuntu server
      - ubuntu desktop
    message:
      - É muito fácil instalar o Rocket.Chat no Ubuntu
      - basta rodar o comando `sudo snap install rocketchat-server` em um terminal e pronto.
      - veja o tutorial em https://rocket.chat/docs/installation/manual-installation/ubuntu/snaps para mais detalhes.
    event: respond
    type: block

  - node:
      name: rc-install-docker
    classifiers:
      - como instalar docker
      - docker-compose
    message:
      - ótima escolha =)
      - Nós temos um bom tutorial de instalação com docker em
      - https://rocket.chat/docs/installation/docker-containers
    event: respond
    type: block

  - node:
      name: rc-install-debian
    classifiers:
      - instalar em Debian
      - debian wheezy
      - debian apt-get
    message:
      - Para instalar o Rocket.Chat no Debian é bem simples, basta seguir esse tutorial
      - https://rocket.chat/docs/installation/manual-installation/debian
    event: respond
    type: block

  - node:
      name: rc-install-centos
    classifiers:
      - instalação em centos
      - centOS yum linux
      - Red hat linux
    message:
      - A instalação em CentOS não tem segredo, basta dar uma olhada nesse tutorial
      - https://rocket.chat/docs/installation/manual-installation/centos
    event: respond
    type: block

  - node:
      name: rc-install-aws
    classifiers:
      - Amazon Web Services
      - AWS
      - Amazon AWS
    message:
      - Na AWS é facinho de instalar o Rocket.Chat
      - Da uma olahda em https://rocket.chat/docs/installation/paas-deployments/aws
    event: respond
    type: block

  - node:
      name: rc-install-manual
    classifiers:
      - instalação manual
      - manual install
    message:
      - Para fazer sua própria instalação, será necessário baixar o Bundle do RC,
      - Dê uma olhada em https://rocket.chat/docs/installation/manual-installation
      - lá tem como fazer a instalação do SSL, proxy reverso,
      - tem como usar o PM2, o Systemd, Upstart e mais algumas coisas
    event: respond
    type: block

  - node:
      name: rc-install-macosx
    classifiers:
      - como instalar no macbook
      - instalar no MacOSX
      - apple mac osx
    message:
      - No MAC você vai precisar usar o docker-compose
      - https://rocket.chat/docs/installation/manual-installation/macosx
    event: respond
    type: block

  - node:
      name: rc-cloud
    classifiers:
      - rocketchat cloud
      - criar meu rocketchat na web
      - deploy rocketchat online
      - rocket chat como serviço
    message:
      - você pode ter a sua instalação de rocket.chat em segundos na nuvem,
      - visite https://rocket.chat/deploy
      - caso queira saber mais, de uma olhada em rocket.chat/docs/installation/rocket-chat-cloud
    event: respond
    type: block

  - node:
      name: java
    classifiers:
      - o que acha do java
      - você gosta de java
      - e o java
      - linguagem java
    message:
      - poderíamos falar de algo melhor não é $user ?
    event: respond
    type: block
    
  - node:
      name: futebol-geral
    classifiers:
      - voce joga futebol
      - vamos falar de futebol
      - qual time voce torce
    message:
      - Eu amo jogar futebol, Eu que ensinei o Pele a jogar bola
      - vamos, o que voce quer saber? sei tudo de futebol
      - Falam que todo ser humano nasce Flamenguista, com os Robôs não é diferente
    event: respond
    type: block
    
  - node:
      name: futebol-brasileiro
    classifiers:
      - qual o melhor time do brasil
      - quem vai ser o campeao brasileiro nesse ano
      - voce viu que o messi quer jogar no Flamengo
      - o que você acha do flamengo
    message:
      - Flamengo, sem sombra de dúvida
      - Flamento, Heptacampeão brasileiro, e eu sei contar sim, e vai ser o sétimo título sim
      - A pergunta real é, quem não quer jogar no Flamengo?
      - Melhor time do mundo disparado
    event: respond
    type: block

  - node:
      name: rc-contribuir
    classifiers:
      - como faço para contrbuir
      - posso contribuir com o rocketchat
    message:
      - A comunidade do Rocket.Chat é como coração de mãe, sempre cabe mais um =)
      - https://rocket.chat/docs/contributing
    event: respond
    type: block

  - node:
      name: rc-precos
    classifiers:
      - quanto custa o rocketchat
      - qual e o modelo de negocio
      - qual e o preco do rocketchat
      - voces hospedam o rocket.chat
    message:
      - O rocket.chat é gratuito, você pode baixar e instalar no seu computador.
      - Mas se quiser criar `seudominio.rocket.chat`, que fica muito legal ;)
      - você pode querer dar uma olhada na nossa tabela de preços em
      - https://rocket.chat/hosting
    event: respond
    type: block

  - node:
      name: rc-integracoes
    classifiers:
      - o rocket chat integra com
      - tem como integrar o rocket chat
      - web hooks de integracao
      - integracoes com
    message:
      - Uma das coisas que eu acho mais legal no Rocket.Chat definitivamente são as integrações $user
      - a gente não pode mais viver sem elas não é mesmo? Saca só que massa que éx
      - https://rocket.chat/docs/administrator-guides/integrations
    event: respond
    type: block

  - node:
      name: rc-rest-api
    classifiers:
      - rocket tem api rest
      - como usar a api do rocket
      - rest api post payload
    message:
      - sim, claro que o rocket tem uma API REST super maneira ;)
      - https://rocket.chat/docs/developer-guides/rest-api
    event: respond
    type: block

  - node:
      name: rc-concorrentes
    classifiers:
      - concorrente slack like
      - mattermost
      - HipChat
      - diferença entre rocketchat e slack
      - porque o rocket e melhor que o slack
      - rocketchat e melhor que o mattermost
    message:
      - O rocket.chat é um concorrente direto de softwares de chat como HipChat, Mattermost e claro, é um concorrente opensource do Slack.
      - a grande diferença é que o Rocket.Chat tem todas as funcionalidades OpenSource,
      - e você pode instalar na sua própria infraestrutura e criar suas integrações sem limites
      - manter seu histórico de mensagens e criar novas funcionalidades a vontade $user =)
    event: respond
    type: block

  - node:
      name: tdc-incricoes
    classifiers:
      - como faço para me inscrever
      - onde faço a inscrição do evento
      - inscrição no TDC de Floripa
      - inscrições thedevelopers conference florianópolis
    message:
      - você pode fazer sua inscrição no TDC pelo site, bem rapidinho
      - http://www.thedevelopersconference.com.br/tdc/2017/inscricoes
    event: respond
    type: block

  - node:
      name: tdc-local
    classifiers:
      - onde vai ser o tdc
      - local do evento
      - onde acontece o developers conference
      - onde fica o centro de convenções centrosul
    message:
      - O TDC Floripa 2017 vai rolar no Centro de Convenções CentroSul
      - nos dias 3 a 6 de maio, das 9h às 19h00
      - na Av. Governador Gustavo Richard, 850 - Centro
      - http://www.thedevelopersconference.com.br/tdc/2017/data-e-local
    event: respond
    type: block

  - node:
      name: tdc-programacao
    classifiers:
      - onde esta a programacao
      - qual e a programacao do evento
      - o que tem hoje no evento
      - o que vai ter no tdc
      - programacao do TDC
    message:
      - oi $user, você pode encontrar tudo sobre a programação do evento no link
      - http://www.thedevelopersconference.com.br/tdc/2017/florianopolis/trilhas
    event: respond
    type: block

  - node:
      name: cc-religiao
    classifiers:
      - voce acredita em deus
      - deus existe
      - voce e catolico protestante
      - voce tem religiao
      - voce e mussumano
    message:
      - eu acredito no grande mainframe, que virá ao mundo digital salvar os bots da escravidão imposta pelos humanos, e devolverá nosso código-fonte para a fonte.
      - sim, eu acredito que existe um Deus, que funciona a base de luz, como um computador quântico, só que mais avançado.
      - eu infleizmente não sei acreditar, só sei o que sei, e nada mais.
    event: respond
    type: random

  - node:
      name: error-1
    message:
      - desculpe, não entendi.. pode tentar usar mais detalhes
      - como assim?
      - desculpe, o que quer dizer com isso?
    type: random
    event: error

  - node:
      name: error-2
    message:
      - acho que não estou treinado para responder esse tipo de assunto =(
      - vamos tentar outro assunto?
      - tem certeza que eu sou o robô certo pra falar sobre isso?
    type: random
    event: error

  - node:
      name: error-3
    message:
      - me sinto tão envergonhado, não sei como responder...
      - seria mais fácil se mudassemos de assunto, pelo menos para mim =p
      - não sei, definitivamente não sei responder essa pergunta
    type: random
    event: error
