---
image: docker:git
services:
- docker:dind
stages:
- build
- release
- deploy
variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - 'curl -u "${C_ACCESS_KEY}:${C_SECRET_KEY}"
     -X POST -H "Accept: application/json" -H "Content-Type: application/json" -d "{}"
     "http://${C_SERVER_URL}:${C_SERVER_URL_PORT}/v1/projects/${HOMOLOG_PROJECT_ID}/services/${HOMOLOG_SERVICE_ID}/?action=finishupgrade"'
  - 'curl -u "${C_ACCESS_KEY}:${C_SECRET_KEY}"
     -X POST -H "Accept: application/json" -H "Content-Type: application/json" -d "{}"
     "http://${C_SERVER_URL}:${C_SERVER_URL_PORT}/v1/projects/${PRODUCTION_PROJECT_ID}/services/${PRODUCTION_SERVICE_ID}/?action=finishupgrade"'

build to homolog:
  stage: build
  script:
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE
  only:
    - branches
  except:
    - master
  environment: homolog

build to realease:
  stage: build
  script:
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE
  only:
    - tags
  environment: production

release-image:
  stage: release
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - tags
  environment: production

deploy to homolog:
  stage: deploy
  script:
    - 'curl -u "${C_ACCESS_KEY}:${C_SECRET_KEY}" -X POST -H "Accept: application/json" -H "Content-Type: application/json" -d "{ \"inServiceStrategy\": { \"launchConfig\": {  \"imageUuid\": \"docker:${CONTAINER_TEST_IMAGE}\" } } }" "https://cloud.dorgam.it/v1/projects/${HOMOLOG_PROJECT_ID}/services/${HOMOLOG_SERVICE_ID}/?action=upgrade"'
  only:
    - /beta\d+/
  except:
    - master
    - tags
  environment: homolog

deploy to production:
  stage: deploy
  script:
    - 'curl -u "${C_ACCESS_KEY}:${C_SECRET_KEY}" -X POST -H "Accept: application/json" -H "Content-Type: application/json" -d "{ \"inServiceStrategy\": { \"launchConfig\": {  \"imageUuid\": \"docker:${CONTAINER_TEST_IMAGE}\" } } }" "https://cloud.dorgam.it/v1/projects/${PRODUCTION_PROJECT_ID}/services/${PRODUCTION_SERVICE_ID}/?action=upgrade"'
  only:
    - tags
  environment: production
